# Generated by Django 5.0 on 2023-12-17 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(max_length=100)),
                ('SiteContact', models.CharField(max_length=100, null=True)),
                ('SiteEmail', models.EmailField(max_length=254)),
                ('SiteAddress', models.CharField(max_length=500, null=True)),
                ('Sitefacebooklink', models.CharField(max_length=300, null=True)),
                ('Sitetwitterlink', models.CharField(max_length=300, null=True)),
                ('Siteinstagramlink', models.CharField(max_length=300, null=True)),
                ('Sitelinkdinlink', models.CharField(max_length=300, null=True)),
                ('logo', models.ImageField(default=None, max_length=200, null=True, upload_to='Global/')),
                ('brochure', models.FileField(null=True, upload_to='brochure/')),
                ('brochure_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Publish', 'Publish'), ('Draft', 'Draft')], max_length=50)),
                ('position', models.IntegerField()),
                ('page_type', models.CharField(blank=True, choices=[('Home', 'Home'), ('Group', 'Group')], max_length=50, null=True)),
                ('title', models.CharField(max_length=200)),
                ('short_desc', models.TextField(null=True)),
                ('short_desc1', models.TextField(default='')),
                ('short_desc2', models.TextField(default=' ')),
                ('short_desc3', models.TextField(default='')),
                ('desc', models.TextField(null=True)),
                ('banner_image', models.ImageField(null=True, upload_to='about/')),
                ('meta_title', models.CharField(max_length=100, null=True)),
                ('meta_keyword', models.CharField(max_length=100, null=True)),
                ('icon_image', models.TextField(null=True)),
                ('slider_image', models.ImageField(null=True, upload_to='about/')),
                ('brochure', models.FileField(null=True, upload_to='brochure/')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('Parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='customadmin.navigation')),
            ],
        ),
    ]
